version: '3.8'

services:
  node-app:
    build: .
    image: node:16-bullseye
    env_file: docker/node/env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/node
    networks:
      - node-network
    command: bash -c "cd node && yarn && npm run dev"

  postgres:
    image: postgres
    restart: always
    env_file: docker/posgres/env
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  dbdata:
    driver: local

networks:
  node-network:
    driver: bridge
